// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaBackQuala;

namespace PruebaBackQuala.Migrations
{
    [DbContext(typeof(DbContextQuala))]
    partial class DbContextQualaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PruebaBackQuala.Models.DataInformationQuala", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MonedaID")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("MonedaID");

                    b.ToTable("DatosInformacionQuala");
                });

            modelBuilder.Entity("PruebaBackQuala.Models.MonedaInformation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("PruebaBackQuala.Models.DataInformationQuala", b =>
                {
                    b.HasOne("PruebaBackQuala.Models.MonedaInformation", "Moneda")
                        .WithMany("DatosQuala")
                        .HasForeignKey("MonedaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("PruebaBackQuala.Models.MonedaInformation", b =>
                {
                    b.Navigation("DatosQuala");
                });
#pragma warning restore 612, 618
        }
    }
}
